### ISSUE TITLE
[Enhancement] Purchase Option on toy-yo.toys 

### ISSUE THREAD

**Issue by rupagurumurthy12** [toy-yo/src#186]
[Purchase Option RG.pdf](https://github.com/toy-yo/src/files/473474/Purchase.Option.RG.pdf)

**Comment by savithaswaminathan** [comment]
Hi Chris,
are you able to take a look at this? I can meet you today or another day this week and walk through.
let me know. This was assigned to sharath but hes been really busy starting last week. Thank you.
