### ISSUE TITLE
Create a rental history

### ISSUE THREAD

**Issue by rupagurumurthy12** [toy-yo/src#190]
The current admin interface does not have a rental history. 
New requirement - 

Create a 'Rental history' page similar to 'Shipping', 'Users' & 'Inventory'.
The rental history page should have the toy name, User name (who checked out the toy), date of checkout, date of return. 

We should be able to sort the page by toys, user, dates. 

Attachement - To upload the current excel sheet that is used to tracking

**Comment by hchris28** [comment]
Savitha - let's talk offline about getting the historical data from the spreadsheet in to the system.
