### ISSUE TITLE
Log in prompts reset password message even with correct password

### ISSUE THREAD

**Issue by savithaswaminathan** [toy-yo/src#81]
Clicking the sign in  with the right user name and password creates the "new password sent to email" message. Clicking sign in the second time logs member in without issue. The email to reset password is also sent.

**Comment by hchris28** [comment]
I just attempted to recreate the issue and could not. After entering my username and password and clicking the Sign In button, I was redirected to the Toyshelf page. I did this on both toyyo and toyyo-prod.
