### ISSUE TITLE
Display member name on Olark chat

### ISSUE THREAD

**Issue by savithaswaminathan** [toy-yo/src#87]
Can we use the olark api to draw the first name of the member who is signed into the site and using olark chat? I believe theres two ways to do this. 
1. upgrading olark membership and including a mandatory question asking for name and email before member messages us
2. set it up to draw the information from member profile.

**Comment by sharathudupa** [comment]
for offline messages, i have enabled it to ask for name and email. as you mentioned the only way to get their name and email when you are online, is to buy the extra subscription of Olark. If you make the changes in the site, it should automatically show up in the chatbox. So closing this issue.
